export enum StudyArea {
    AI = "AI",
    Arts = "Arts",
    Building = "Building",
    Business = "Business",
    Communication = "Communication",
    Computing = "Computing",
    Design = "Design",
    Education = "Education",
    Engineering = "Engineering",
    Law = "Law",
    Medicine = "Medicine",
    Music = "Music",
    Philosophy = "Philosophy",
    Psychology = "Psychology",
    Science = "Science",
    SocialPolicy = "SocialPolicy",
    SocialSciences = "SocialSciences",
    SocialWork = "SocialWork",
    Sociology = "Sociology",
    Sports = "Sports",
}
